# Generated by Django 4.0.4 on 2022-04-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='file',
        ),
        migrations.AddField(
            model_name='scan',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='images/'),
        ),
    ]
