# Generated by Django 4.0.4 on 2022-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_scan_file_scan_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='scans/'),
        ),
    ]
